
server:
  port: 8083

spring:
  application:
    name: framework
  datasource:
    url: jdbc:mysql://DESKTOP-QLADQDP:3306/lanjing?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  mvc:
    hiddenmethod:
      filter:
        enabled: false

  thymeleaf:
    cache: false
    mode: LEGACYHTML5




feign:
  hystrix:
    enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka

mybatis:
  mapper-locations: classpath*:mybatis/*/*Mapper.xml
  type-aliases-package: com.jk.entity.dept
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
