server:
  port: 8766

spring:
  application:
    name: whale-emp
  datasource:
    url: jdbc:mysql://DESKTOP-QLADQDP/lanjing?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 5000


  mvc:
    hiddenmethod:
      filter:
        enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka


mybatis:
  mapper-locations: classpath*:mybatis/*/*Mapper.xml
  type-aliases-package: com.jk.entity.emp
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
