
server:
  port: 8082

spring:
  application:
    name: web

  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册


  mvc:
    hiddenmethod:
      filter:
        enabled: false

  thymeleaf:
    cache: false
    mode: LEGACYHTML5


ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka
